
# Numpy In Python

## Introduction to NumPy

In this video, we are going to discuss a very important library called NumPy. Up to this point, we have covered advanced Python concepts such as iterators, generators, and decorators. Now, we are moving to a new module: data analysis with Python. Here, we will focus on libraries like NumPy, Pandas, and visualization libraries such as Matplotlib and Seaborn, which are fundamentally used for data analysis. Out of all these libraries, NumPy is extremely important, as it is also used in deep learning modules. With NumPy, we can create arrays, work with matrices, and perform mathematical operations very efficiently.

## Installing NumPy

Whenever you create a new environment, NumPy is not installed by default. There are two ways to install it:

- Update the requirements.txt file and run `pip install -r requirements.txt` in your terminal.
- Directly in the Jupyter notebook, you can run `pip install numpy`.

Once installed, you can proceed to use NumPy in your projects.

## Importing NumPy

To use NumPy, you need to import it. The common convention is to import it as `np`, which serves as an alias and allows you to use `np.` instead of typing `numpy.` everywhere.

```python
import numpy as np


## Creating Arrays

Let us create a one-dimensional array (1D array) using NumPy. We use the `np.array` function, which can take a list or tuple as input.

```python
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
```

## Array Type and Shape

Although the array may look like a list, it is actually a NumPy `ndarray`. You can check its type and shape using the following commands:

```python
print(type(arr1))
print(arr1.shape)
```

## Reshaping Arrays

If you want to convert a 1D array into a 2D array, you can use the reshape method. For example, reshaping to `(1, 5)` means one row and five columns. The total number of elements must remain the same.

```python
arr2 = arr1.reshape(1, 5)
print(arr2)
print(arr2.shape)
```

## Creating 2D Arrays Directly

You can also create a two-dimensional array directly by passing a nested list to `np.array`.

```python
arr2 = np.array([[1, 2, 3, 4, 5], [2, 3, 4, 5, 6]])
print(arr2)
print(arr2.shape)
```

## Using Inbuilt Functions to Create Arrays

NumPy provides several inbuilt functions to create arrays quickly, such as `arange`, `ones`, and `eye`.

```python
arr = np.arange(0, 10, 2)
print(arr)
arr_reshaped = arr.reshape(5, 1)
print(arr_reshaped)
```

```python
ones_arr = np.ones((3, 4))
print(ones_arr)
```

```python
identity_matrix = np.eye(3, 2)
print(identity_matrix)
```

## Array Attributes

NumPy arrays have several useful attributes such as `shape`, `ndim`, `size`, `dtype`, and `itemsize`.

```python
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)
```

## Vectorized Operations

NumPy supports vectorized operations, allowing you to perform element-wise arithmetic directly on arrays.

```python
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)
```

## Universal Functions

NumPy provides universal functions (ufuncs) that operate element-wise on arrays, such as `sqrt`, `exp`, `sin`, and `log`.

```python
arr = np.array([1, 2, 3, 4, 5, 6])
print(np.sqrt(arr))
print(np.exp(arr))
print(np.sin(arr))
print(np.log(arr))
```

## Array Slicing and Indexing

You can perform slicing and indexing operations on NumPy arrays, similar to Python lists, but with more power for multi-dimensional arrays.

```python
arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])
print(arr)
```

### Accessing Elements and Slices

You can access elements using row and column indices. Indexing starts from zero. For example, to access the element in the first row and first column, use `arr[0, 0]`. To access subarrays, use slicing.

```python
print(arr[0, 0])
print(arr[1:, 2:])
print(arr[1:, :2])
print(arr[1:, 1:3])
```

## Modifying Array Elements

You can modify elements or slices of a NumPy array by assigning new values.

```python
arr[0, 0] = 100
print(arr)
arr[1:, :] = 100
print(arr)
```

## Statistical Operations and Normalization

NumPy provides functions for statistical operations such as mean, median, standard deviation, and variance. Normalization is a common operation where data is transformed to have a mean of zero and a standard deviation of one.

```python
data = np.array([1, 2, 3, 4, 5])
mean = np.mean(data)
std = np.std(data)
normalized_data = (data - mean) / std
print(normalized_data)
```

```python
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))
```

## Logical Operations

NumPy allows you to perform logical operations on arrays. For example, you can check which elements are greater than a certain value and use the result to filter the array.

```python
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(data > 5)
print(data[data > 5])
print(data[(data >= 5) & (data <= 8)])
```

## Conclusion

In this session, we discussed NumPy, including how to create, reshape, and manipulate arrays, perform vectorized and universal operations, slice and index arrays, modify elements, and apply statistical and logical operations. NumPy is a foundational tool for scientific computing and data analysis in Python, and its concepts will be used extensively in future lessons, including machine learning and data analysis with Pandas.

## Key Takeaways

* NumPy is a fundamental library for scientific computing in Python, providing support for arrays, matrices, and mathematical functions.
* Arrays can be created, reshaped, and manipulated using various NumPy functions such as `np.array`, `reshape`, `arange`, `ones`, and `eye`.
* NumPy supports vectorized operations, universal functions, and logical operations for efficient computation.
* Array slicing, indexing, and modification are essential for data manipulation, and NumPy offers powerful tools for these tasks.



In [13]:
!pip install numpy


In [14]:
import numpy as np


In [15]:

## create arrays using numpy 

## create a 1D array

arr1 = np.array([1,2,3,4,5,6])
print(arr1)
print(type(arr1))
print(arr1.shape)



[1 2 3 4 5 6]
<class 'numpy.ndarray'>
(6,)


In [16]:
arr2 = arr1
print(arr2)

# arr2.reshape(1,5) # 1 row and 5 col
# ->"message": "ValueError: cannot reshape array of size 6 into shape (1,5)",

print(arr2.reshape(1,6))
print(arr2.shape)

[1 2 3 4 5 6]
[[1 2 3 4 5 6]]
(6,)


In [ ]:
arr = np.array([[1,2,3,4],[3,2,2,4],[2,4,7,7]])
print(arr[0, 0]) # arr[0][0] same
print(arr[1:, 2:])
print(arr[1:, :2])
print(arr[1:, 1:3])

1
[[2 4]
 [7 7]]
[[3 2]
 [2 4]]
[[2 2]
 [4 7]]
