In [49]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns 

%matplotlib inline

In [50]:
from sklearn.datasets import make_classification

In [51]:
# X,y = make_classification(n_classes=4,n_features=10,n_samples=10000,random_state=45)

# ❌ Error in `make_classification`

## 🚨 Problem

```python
from sklearn.datasets import make_classification

X, y = make_classification(
    n_classes=4,
    n_features=10,
    n_samples=10000,
    random_state=45
)
Error:
ValueError: n_classes(4) * n_clusters_per_class(2) must be smaller or equal 2**n_informative(2)=4
🔍 Why this happens

Default parameters used internally:

n_informative = 2
n_clusters_per_class = 2
Required Constraint
n_classes×n_clusters_per_class≤2
n_informative
Substituting values:
4×2=8
2x2<=4

❌ Since 8 > 4, the configuration is invalid

✅ Fixes
✔ Option 1: Increase n_informative (Recommended)
X, y = make_classification(
    n_classes=4,
    n_features=10,
    n_samples=10000,
    n_informative=3,
    random_state=45
)
✔ Option 2: Reduce n_clusters_per_class
X, y = make_classification(
    n_classes=4,
    n_features=10,
    n_samples=10000,
    n_clusters_per_class=1,
    random_state=45
)
✔ Option 3: Better realistic configuration
X, y = make_classification(
    n_samples=10000,
    n_features=10,
    n_informative=5,
    n_redundant=2,
    n_classes=4,
    n_clusters_per_class=1,
    random_state=45
)
🧠 Key Insight
n_informative controls how many features actually define class separation
Increasing number of classes or clusters requires higher informative dimensions
Otherwise, class separation becomes mathematically impossible
🎯 Rule to Remember

Increase n_informative when increasing n_classes or n_clusters_per_class

In [52]:
X, y = make_classification(
    n_classes=4,
    n_features=10,
    n_samples=10000,
    n_informative=3,
    random_state=45
)

In [53]:
pd.DataFrame(X)

,0,1,2,3,4,5,6,7,8,9
0,1.566757,-0.093809,-1.957284,-1.348249,-2.346783,-0.128094,1.424827,-1.243051,-0.392157,1.921330
1,-1.103240,1.408646,-0.804838,1.275784,2.789410,-0.947934,1.122768,-0.875683,0.870415,-2.639412
2,-1.592452,-1.272894,0.327399,-1.506422,-3.004698,0.742380,-0.283378,0.530923,-0.115886,-1.105916
3,-2.787118,1.135830,-2.218301,0.620304,0.869381,-0.483861,-0.457523,0.981434,1.357977,0.045032
4,0.630925,0.840404,-1.608035,-0.438310,0.191382,-1.038066,-0.959555,0.169961,0.117725,0.538661
...,...,...,...,...,...,...,...,...,...,...
9995,0.787919,-0.123651,0.958180,-1.028536,-0.073969,-0.929275,-0.547951,1.688230,-2.606940,0.979287
9996,0.354494,-1.158350,0.857686,0.076559,-1.550801,1.544164,0.818599,-0.749298,-0.538292,0.534226
9997,-0.829317,-0.355619,-0.195244,0.071443,-0.790438,0.680487,-0.955573,-0.788191,-0.289947,-0.287194
9998,0.701894,0.350293,0.583104,-1.814384,0.141922,-2.113521,1.708767,0.331567,0.877812,-0.091494


In [54]:
print(y)

[0 2 1 ... 1 2 2]


In [55]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y, test_size=.3,random_state=10)

In [56]:
from sklearn.linear_model import LogisticRegression

logreg =LogisticRegression()

In [57]:
logreg.fit(X_train,y_train)

LogisticRegression()

In [58]:
y_pred =  logreg.predict(X_test)
y_pred

array([1, 3, 3, ..., 2, 0, 3])

In [59]:
logreg.predict_proba(X_test)

array([[0.04535354, 0.62950041, 0.01943634, 0.30570971],
       [0.01003618, 0.39190656, 0.01507704, 0.58298022],
       [0.01197827, 0.28024008, 0.02487701, 0.68290463],
       ...,
       [0.21019034, 0.04037723, 0.69633362, 0.0530988 ],
       [0.65914735, 0.10399545, 0.22320845, 0.01364874],
       [0.00390681, 0.22569778, 0.0067119 , 0.76368351]])

In [60]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

score = accuracy_score(y_test,y_pred)
print("accuracy: " ,score)

print(confusion_matrix(y_test,y_pred))

print(classification_report(y_test,y_pred))

accuracy:  0.723
[[532  87 147   5]
 [ 71 522  39 100]
 [161   6 537  50]
 [  6  94  65 578]]
              precision    recall  f1-score   support

           0       0.69      0.69      0.69       771
           1       0.74      0.71      0.72       732
           2       0.68      0.71      0.70       754
           3       0.79      0.78      0.78       743

    accuracy                           0.72      3000
   macro avg       0.72      0.72      0.72      3000
weighted avg       0.72      0.72      0.72      3000



# GridSearchCV


In [61]:
# GridSearchCV

model_estimator = LogisticRegression()
param = [
    {
        'penalty':['l2'],
        'solver': ['newton-cg','lbfgs','sag'],
        'C':[100, 10, 1.0, 0.1, 0.01]
    },
    {
        'penalty':['l1'],
        'solver': ['liblinear','saga'],
        'C':[100, 10, 1.0, 0.1, 0.01]
    },
    {
        'penalty':['elasticnet'],
        'solver': ['saga'],
        'C':[100, 10, 1.0, 0.1, 0.01]
    }
]



In [62]:
from sklearn.model_selection import StratifiedKFold,GridSearchCV,RandomizedSearchCV

gridCV = GridSearchCV(estimator=model_estimator,
                       param_grid=param, 
                       cv = StratifiedKFold(n_splits=5,shuffle=False), 
                       scoring ='accuracy')

In [63]:
gridCV.fit(X_train,y_train)

d:\Anaconda\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
d:\Anaconda\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
d:\Anaconda\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
d:\Anaconda\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
d:\Anaconda\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
d:\Anaconda\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
d:\Anacond

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(),
             param_grid=[{'C': [100, 10, 1.0, 0.1, 0.01], 'penalty': ['l2'],
                          'solver': ['newton-cg', 'lbfgs', 'sag']},
                         {'C': [100, 10, 1.0, 0.1, 0.01], 'penalty': ['l1'],
                          'solver': ['liblinear', 'saga']},
                         {'C': [100, 10, 1.0, 0.1, 0.01],
                          'penalty': ['elasticnet'], 'solver': ['saga']}],
             scoring='accuracy')

In [64]:
gridCV

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(),
             param_grid=[{'C': [100, 10, 1.0, 0.1, 0.01], 'penalty': ['l2'],
                          'solver': ['newton-cg', 'lbfgs', 'sag']},
                         {'C': [100, 10, 1.0, 0.1, 0.01], 'penalty': ['l1'],
                          'solver': ['liblinear', 'saga']},
                         {'C': [100, 10, 1.0, 0.1, 0.01],
                          'penalty': ['elasticnet'], 'solver': ['saga']}],
             scoring='accuracy')

In [65]:
gridCV.best_params_

{'C': 0.01, 'penalty': 'l2', 'solver': 'newton-cg'}

In [66]:
gridCV.best_score_

np.float64(0.7161428571428571)

In [67]:
y_pred_grid = gridCV.predict(X_test) 

In [68]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

score = accuracy_score(y_test,y_pred_grid)
print(score)

print(confusion_matrix(y_test,y_pred_grid))

print(classification_report(y_test,y_pred_grid))

0.7233333333333334
[[532  86 149   4]
 [ 70 523  42  97]
 [160   6 538  50]
 [  6  93  67 577]]
              precision    recall  f1-score   support

           0       0.69      0.69      0.69       771
           1       0.74      0.71      0.73       732
           2       0.68      0.71      0.69       754
           3       0.79      0.78      0.78       743

    accuracy                           0.72      3000
   macro avg       0.72      0.72      0.72      3000
weighted avg       0.72      0.72      0.72      3000



# RandomizedSearch CV


In [69]:
# RandomizedSearch CV

randomCV = RandomizedSearchCV(
    estimator= model_estimator,
    param_distributions= param,
    cv= 5,
    scoring= 'accuracy'
)

In [70]:
randomCV

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions=[{'C': [100, 10, 1.0, 0.1, 0.01],
                                         'penalty': ['l2'],
                                         'solver': ['newton-cg', 'lbfgs',
                                                    'sag']},
                                        {'C': [100, 10, 1.0, 0.1, 0.01],
                                         'penalty': ['l1'],
                                         'solver': ['liblinear', 'saga']},
                                        {'C': [100, 10, 1.0, 0.1, 0.01],
                                         'penalty': ['elasticnet'],
                                         'solver': ['saga']}],
                   scoring='accuracy')

In [71]:
randomCV.fit(X_train,y_train)

d:\Anaconda\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
d:\Anaconda\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
d:\Anaconda\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
d:\Anaconda\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
d:\Anaconda\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions=[{'C': [100, 10, 1.0, 0.1, 0.01],
                                         'penalty': ['l2'],
                                         'solver': ['newton-cg', 'lbfgs',
                                                    'sag']},
                                        {'C': [100, 10, 1.0, 0.1, 0.01],
                                         'penalty': ['l1'],
                                         'solver': ['liblinear', 'saga']},
                                        {'C': [100, 10, 1.0, 0.1, 0.01],
                                         'penalty': ['elasticnet'],
                                         'solver': ['saga']}],
                   scoring='accuracy')

In [72]:
y_pred_rand = randomCV.predict(X_test)

In [73]:
randomCV.best_params_

{'solver': 'newton-cg', 'penalty': 'l2', 'C': 0.01}

In [74]:
randomCV.best_score_

np.float64(0.7161428571428571)

In [75]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

score = accuracy_score(y_test,y_pred_rand)
print(score)

print(confusion_matrix(y_test,y_pred_rand))

print(classification_report(y_test,y_pred_rand))

0.7233333333333334
[[532  86 149   4]
 [ 70 523  42  97]
 [160   6 538  50]
 [  6  93  67 577]]
              precision    recall  f1-score   support

           0       0.69      0.69      0.69       771
           1       0.74      0.71      0.73       732
           2       0.68      0.71      0.69       754
           3       0.79      0.78      0.78       743

    accuracy                           0.72      3000
   macro avg       0.72      0.72      0.72      3000
weighted avg       0.72      0.72      0.72      3000



In [76]:
if randomCV.best_score_ > gridCV.best_score_:
    print("yes")
else:
    print("no")

no
