# Logistic Regression


In [105]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns 

%matplotlib inline

In [106]:
from sklearn.datasets import make_classification



In [107]:
# make datasets

X,y=make_classification(n_samples=1000,n_classes=2,n_features=10,random_state=20)

In [108]:
pd.DataFrame(X)

,0,1,2,3,4,5,6,7,8,9
0,-0.772283,0.196706,1.649498,0.471559,0.322462,-0.143971,-0.873637,0.114953,0.754038,1.316466
1,1.466115,-0.569985,-0.490921,-1.170983,1.278384,-0.720606,0.680824,-0.431002,1.054122,-1.378789
2,0.265159,2.354382,-1.302640,0.283290,-0.497433,-1.736997,0.888013,-0.078976,-0.089218,-1.298991
3,1.054882,0.830666,0.012437,-0.435215,-1.780593,1.953013,-1.237963,0.662300,-0.005446,2.381620
4,-0.806635,-0.780728,1.227786,-0.195062,-0.624200,1.051022,-0.099346,0.160575,-0.496138,0.302153
...,...,...,...,...,...,...,...,...,...,...
995,-0.894265,-1.605784,-0.095059,1.710907,1.303194,0.323110,-0.830412,-0.113191,-1.453720,1.021412
996,-0.015521,-0.916188,0.786272,-0.120857,2.091906,0.031402,-0.674116,-0.322670,0.076854,0.590644
997,0.109996,0.155598,0.613506,0.031932,1.957641,0.346085,-0.887701,-0.247003,-0.549994,0.961649
998,0.369745,0.898519,-1.651663,0.554387,-1.226184,-1.243076,-0.687002,0.420673,-0.039926,1.376583


In [109]:
y # binary classification

array([1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0,

In [110]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y, test_size=.3,random_state=10)

In [111]:
# model training

from  sklearn.linear_model import LogisticRegression

logistic_reg =LogisticRegression()

In [112]:
logistic_reg.fit(X_train,y_train)

LogisticRegression()

In [113]:
y_pred = logistic_reg.predict(X_test)

y_pred

array([0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1])

In [114]:
logistic_reg.predict_proba(X_test)

array([[9.97937678e-01, 2.06232160e-03],
       [5.30735957e-01, 4.69264043e-01],
       [2.85678944e-06, 9.99997143e-01],
       [8.71744736e-03, 9.91282553e-01],
       [9.17697803e-06, 9.99990823e-01],
       [8.53906610e-01, 1.46093390e-01],
       [2.55770361e-01, 7.44229639e-01],
       [5.61296781e-02, 9.43870322e-01],
       [2.67652806e-01, 7.32347194e-01],
       [8.93142133e-01, 1.06857867e-01],
       [4.97480220e-01, 5.02519780e-01],
       [9.79052523e-01, 2.09474772e-02],
       [9.99773461e-01, 2.26538590e-04],
       [9.84237401e-01, 1.57625995e-02],
       [1.18674982e-01, 8.81325018e-01],
       [2.12865754e-02, 9.78713425e-01],
       [1.32152386e-02, 9.86784761e-01],
       [9.96658006e-01, 3.34199375e-03],
       [9.77727586e-01, 2.22724143e-02],
       [5.16485362e-04, 9.99483515e-01],
       [7.14671913e-02, 9.28532809e-01],
       [9.95622911e-01, 4.37708925e-03],
       [9.91286960e-01, 8.71304012e-03],
       [9.97162456e-01, 2.83754364e-03],
       [9.873167

In [115]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

score = accuracy_score(y_test,y_pred)
print(score)

print(confusion_matrix(y_test,y_pred))

print(classification_report(y_test,y_pred))

0.9366666666666666
[[143  12]
 [  7 138]]
              precision    recall  f1-score   support

           0       0.95      0.92      0.94       155
           1       0.92      0.95      0.94       145

    accuracy                           0.94       300
   macro avg       0.94      0.94      0.94       300
weighted avg       0.94      0.94      0.94       300



# hypermeter tuning and cross validation

# GridSearch CV

In [116]:
model =  LogisticRegression()
penalty = ['l2','l1','elasticnet']
c_value = [100,10,1.0,0.1,0.01]
solver =  ['newton-cg', 'lbfgs','liblinear', 'sag', 'saga']

In [117]:
param =dict(penalty= penalty, C = c_value, solver = solver)
print(param)

{'penalty': ['l2', 'l1', 'elasticnet'], 'C': [100, 10, 1.0, 0.1, 0.01], 'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga']}


In [118]:
# # penalty = ['l2', 'l1', 'elasticnet']
# # solver = ['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga']

# # 👉 This will cause invalid combinations like:

# # 'l1' with 'lbfgs' ❌
# # 'elasticnet' without 'saga' ❌


# param_grid = [
#     {
#         'penalty': ['l2'],
#         'solver': ['newton-cg', 'lbfgs', 'sag'],
#         'C': [100, 10, 1.0, 0.1, 0.01]
#     },
#     {
#         'penalty': ['l1'],
#         'solver': ['liblinear', 'saga'],
#         'C': [100, 10, 1.0, 0.1, 0.01]
#     },
#     {
#         'penalty': ['elasticnet'],
#         'solver': ['saga'],
#         'C': [100, 10, 1.0, 0.1, 0.01],
#         'l1_ratio': [0.5]
#     }
# ]

In [ ]:
# Straitified  K fold
from sklearn.model_selection import StratifiedKFold

cv  = StratifiedKFold(n_splits=5,shuffle=False) # Cross Validation


In [120]:
## gridSearchCV

from sklearn.model_selection import GridSearchCV

grid = GridSearchCV(estimator=model,param_grid=param,scoring= 'accuracy',cv =cv, n_jobs =-1)

In [121]:
grid

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'penalty': ['l2', 'l1', 'elasticnet'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                    'saga']},
             scoring='accuracy')

In [122]:
X_train.shape

(700, 10)

In [123]:
print(type(y_train))
print(np.shape(y_train))

<class 'numpy.ndarray'>
(700,)


In [124]:
grid.fit(X_train,y_train)

d:\Anaconda\Lib\site-packages\sklearn\model_selection\_validation.py:528: FitFailedWarning: 
200 fits failed out of a total of 375.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "d:\Anaconda\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Anaconda\Lib\site-packages\sklearn\base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "d:\Anaconda\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1193, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'penalty': ['l2', 'l1', 'elasticnet'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                    'saga']},
             scoring='accuracy')

In [125]:
grid.best_params_

{'C': 0.1, 'penalty': 'l1', 'solver': 'liblinear'}

In [126]:
grid.best_score_

np.float64(0.9442857142857143)

In [127]:
y_pred_grid = grid.predict(X_test) 

In [130]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

score = accuracy_score(y_test,y_pred_grid)
print(score)

print(confusion_matrix(y_test,y_pred_grid))

print(classification_report(y_test,y_pred_grid))

0.9466666666666667
[[145  10]
 [  6 139]]
              precision    recall  f1-score   support

           0       0.96      0.94      0.95       155
           1       0.93      0.96      0.95       145

    accuracy                           0.95       300
   macro avg       0.95      0.95      0.95       300
weighted avg       0.95      0.95      0.95       300



# Randomized SearchCV

In [135]:
 from sklearn.model_selection import RandomizedSearchCV

 randomcv = RandomizedSearchCV(estimator=model, param_distributions=param,cv = 5,scoring = 'accuracy' )

In [136]:
randomcv

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [100, 10, 1.0, 0.1, 0.01],
                                        'penalty': ['l2', 'l1', 'elasticnet'],
                                        'solver': ['newton-cg', 'lbfgs',
                                                   'liblinear', 'sag',
                                                   'saga']},
                   scoring='accuracy')

In [142]:
randomcv.fit(X_train,y_train)

d:\Anaconda\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
d:\Anaconda\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
d:\Anaconda\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
d:\Anaconda\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
d:\Anaconda\Lib\site-packages\sklearn\model_selection\_validation.py:528: FitFailedWarning: 
25 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the 

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [100, 10, 1.0, 0.1, 0.01],
                                        'penalty': ['l2', 'l1', 'elasticnet'],
                                        'solver': ['newton-cg', 'lbfgs',
                                                   'liblinear', 'sag',
                                                   'saga']},
                   scoring='accuracy')

In [143]:
randomcv.best_params_

{'solver': 'saga', 'penalty': 'l2', 'C': 1.0}

In [144]:
randomcv.best_score_

np.float64(0.9385714285714286)

In [145]:
y_pred_rand =randomcv.predict(X_test)

In [146]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

score = accuracy_score(y_test,y_pred_rand)
print(score)

print(confusion_matrix(y_test,y_pred_rand))

print(classification_report(y_test,y_pred_rand))

0.9366666666666666
[[143  12]
 [  7 138]]
              precision    recall  f1-score   support

           0       0.95      0.92      0.94       155
           1       0.92      0.95      0.94       145

    accuracy                           0.94       300
   macro avg       0.94      0.94      0.94       300
weighted avg       0.94      0.94      0.94       300



In [148]:
if randomcv.best_score_ > grid.best_score_:
    print("yes")
else:
    print("no")

no
